// <auto-generated />
using System;
using Devices.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devices.Infrastructure.Migrations
{
    [DbContext(typeof(DevicesDBContext))]
    [Migration("20251102175153_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devices.Domain.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceNumber")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("This is unique name for device");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementConfigurationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("TimestampConfigurationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DeviceNumber")
                        .IsUnique();

                    b.HasIndex("LocationID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TimestampConfigurationID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Devices.Domain.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Name of location, for example: 'Kitchen'...");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Devices.Domain.Models.MeasurementConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AirIonizationLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Airflow")
                        .HasColumnType("bit");

                    b.Property<bool>("Ammonia")
                        .HasColumnType("bit");

                    b.Property<bool>("CarbonDioxide")
                        .HasColumnType("bit");

                    b.Property<bool>("CarbonMonoxide")
                        .HasColumnType("bit");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<bool>("Formaldehyde")
                        .HasColumnType("bit");

                    b.Property<bool>("Humidity")
                        .HasColumnType("bit");

                    b.Property<bool>("Illuminance")
                        .HasColumnType("bit");

                    b.Property<bool>("Oxygen")
                        .HasColumnType("bit");

                    b.Property<bool>("Ozone")
                        .HasColumnType("bit");

                    b.Property<bool>("PM1")
                        .HasColumnType("bit");

                    b.Property<bool>("PM10")
                        .HasColumnType("bit");

                    b.Property<bool>("PM25")
                        .HasColumnType("bit");

                    b.Property<bool>("Radon")
                        .HasColumnType("bit");

                    b.Property<bool>("SoundLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Temperature")
                        .HasColumnType("bit");

                    b.Property<bool>("VolatileOrganicCompounds")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("DeviceID")
                        .IsUnique();

                    b.ToTable("MeasurementConfigurations");
                });

            modelBuilder.Entity("Devices.Domain.Models.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Devices.Domain.Models.TimestampConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Timestamp measurement configuration stored in CRON format");

                    b.HasKey("ID");

                    b.ToTable("TimestampConfigurations");
                });

            modelBuilder.Entity("Devices.Domain.Models.Device", b =>
                {
                    b.HasOne("Devices.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devices.Domain.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devices.Domain.Models.TimestampConfiguration", "TimestampConfiguration")
                        .WithMany()
                        .HasForeignKey("TimestampConfigurationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Status");

                    b.Navigation("TimestampConfiguration");
                });

            modelBuilder.Entity("Devices.Domain.Models.MeasurementConfiguration", b =>
                {
                    b.HasOne("Devices.Domain.Models.Device", "Device")
                        .WithOne("MeasurementConfiguration")
                        .HasForeignKey("Devices.Domain.Models.MeasurementConfiguration", "DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Devices.Domain.Models.Device", b =>
                {
                    b.Navigation("MeasurementConfiguration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
