namespace Measurements.Application.DTOs;

public record CreateMeasurementSetDTO(Guid DeviceNumber, DateTime RegisterDate,
    MeasurementDTO? Temperature,
    MeasurementDTO? Humidity,
    MeasurementDTO? CO2,
    MeasurementDTO? VOC,
    MeasurementDTO? ParticulateMatter1,
    MeasurementDTO? ParticulateMatter2v5,
    MeasurementDTO? ParticulateMatter10,
    MeasurementDTO? Formaldehyde,
    MeasurementDTO? CO,
    MeasurementDTO? O3,
    MeasurementDTO? Ammonia,
    MeasurementDTO? Airflow,
    MeasurementDTO? AirIonizationLevel,
    MeasurementDTO? O2,
    MeasurementDTO? Radon,
    MeasurementDTO? Illuminance,
    MeasurementDTO? SoundLevel);
public record MeasurementSetDTO(Guid Id, Guid DeviceNumber, DateTime RegisterDate,
    MeasurementDTO? Temperature,
    MeasurementDTO? Humidity,
    MeasurementDTO? CO2,
    MeasurementDTO? VOC,
    MeasurementDTO? ParticulateMatter1,
    MeasurementDTO? ParticulateMatter2v5,
    MeasurementDTO? ParticulateMatter10,
    MeasurementDTO? Formaldehyde,
    MeasurementDTO? CO,
    MeasurementDTO? O3,
    MeasurementDTO? Ammonia,
    MeasurementDTO? Airflow,
    MeasurementDTO? AirIonizationLevel,
    MeasurementDTO? O2,
    MeasurementDTO? Radon,
    MeasurementDTO? Illuminance,
    MeasurementDTO? SoundLevel);

public record UpdateMeasurementSetDTO(Guid Id,
    Guid? DeviceNumber,
    MeasurementDTO? Temperature,
    MeasurementDTO? Humidity,
    MeasurementDTO? CO2,
    MeasurementDTO? VOC,
    MeasurementDTO? ParticulateMatter1,
    MeasurementDTO? ParticulateMatter2v5,
    MeasurementDTO? ParticulateMatter10,
    MeasurementDTO? Formaldehyde,
    MeasurementDTO? CO,
    MeasurementDTO? O3,
    MeasurementDTO? Ammonia,
    MeasurementDTO? Airflow,
    MeasurementDTO? AirIonizationLevel,
    MeasurementDTO? O2,
    MeasurementDTO? Radon,
    MeasurementDTO? Illuminance,
    MeasurementDTO? SoundLevel);