// <auto-generated />
using System;
using Emulators.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emulators.Infrastructure.Migrations
{
    [DbContext(typeof(EmulatorsDBContext))]
    [Migration("20251116204452_Removed-unique-chart-name")]
    partial class Removeduniquechartname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emulators.Domain.Models.ChartTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Name of chart, for example 'Temperature' it should represent measurement type.");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Represents unit of Y axis");

                    b.HasKey("ID");

                    b.ToTable("ChartTemplates");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceNumber")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("This is unique name for device");

                    b.Property<double>("Spread")
                        .HasColumnType("float")
                        .HasComment("Measurement value spread, expressed in percentage.");

                    b.HasKey("ID");

                    b.HasIndex("DeviceNumber")
                        .IsUnique();

                    b.ToTable("Devices", t =>
                        {
                            t.HasCheckConstraint("CK_Device_Spread_Range", "Spread >= 0 AND Spread <= 100");
                        });
                });

            modelBuilder.Entity("Emulators.Domain.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Offset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChartTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ChartTemplateID");

                    b.HasIndex("LocationID");

                    b.ToTable("Offsets");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChartTemplateID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ChartTemplateID");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Offset", b =>
                {
                    b.HasOne("Emulators.Domain.Models.ChartTemplate", "ChartTemplate")
                        .WithMany()
                        .HasForeignKey("ChartTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emulators.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartTemplate");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.HasOne("Emulators.Domain.Models.ChartTemplate", "ChartTemplate")
                        .WithMany()
                        .HasForeignKey("ChartTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
