// <auto-generated />
using System;
using Emulators.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emulators.Infrastructure.Migrations
{
    [DbContext(typeof(EmulatorsDBContext))]
    [Migration("20251112090514_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emulators.Domain.Models.Bias", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("TimeOffset")
                        .HasColumnType("int");

                    b.Property<double>("ValueOffset")
                        .HasColumnType("float");

                    b.Property<double>("ValueSpread")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DeviceID");

                    b.HasIndex("LocationID");

                    b.HasIndex("MeasurementTypeID");

                    b.ToTable("Biases");
                });

            modelBuilder.Entity("Emulators.Domain.Models.ChartTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MeasurementTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementTypeID")
                        .IsUnique();

                    b.ToTable("ChartTemplates");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceNumber")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("This is unique name for device");

                    b.HasKey("ID");

                    b.HasIndex("DeviceNumber")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Emulators.Domain.Models.MeasurementType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChartTemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MeasurementTypes");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChartTemplateID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ChartTemplateID");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Bias", b =>
                {
                    b.HasOne("Emulators.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emulators.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emulators.Domain.Models.MeasurementType", "MeasurementType")
                        .WithMany()
                        .HasForeignKey("MeasurementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Location");

                    b.Navigation("MeasurementType");
                });

            modelBuilder.Entity("Emulators.Domain.Models.ChartTemplate", b =>
                {
                    b.HasOne("Emulators.Domain.Models.MeasurementType", "MeasurementType")
                        .WithOne("ChartTemplate")
                        .HasForeignKey("Emulators.Domain.Models.ChartTemplate", "MeasurementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementType");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.HasOne("Emulators.Domain.Models.ChartTemplate", "ChartTemplate")
                        .WithMany()
                        .HasForeignKey("ChartTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartTemplate");
                });

            modelBuilder.Entity("Emulators.Domain.Models.MeasurementType", b =>
                {
                    b.Navigation("ChartTemplate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
