// <auto-generated />
using System;
using Emulators.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emulators.Infrastructure.Migrations
{
    [DbContext(typeof(EmulatorsDBContext))]
    [Migration("20251114155037_Location can have multiple charts")]
    partial class Locationcanhavemultiplecharts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emulators.Domain.Models.ChartTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Name of chart, for example 'Temperature' it should represent measurement type.");

                    b.Property<int>("TimeOffset")
                        .HasColumnType("int")
                        .HasComment("Move chart to the right or left side.");

                    b.Property<double>("ValueOffset")
                        .HasColumnType("float")
                        .HasComment("Boost all values of this chart.");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChartTemplates");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("DeviceNumber")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("This is unique name for device");

                    b.Property<double>("Spread")
                        .HasColumnType("float")
                        .HasComment("Measurement value spread, expressed in percentage.");

                    b.HasKey("ID");

                    b.HasIndex("DeviceNumber")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChartTemplateID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ChartTemplateID");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Emulators.Domain.Models.ChartTemplate", b =>
                {
                    b.HasOne("Emulators.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Emulators.Domain.Models.Sample", b =>
                {
                    b.HasOne("Emulators.Domain.Models.ChartTemplate", "ChartTemplate")
                        .WithMany()
                        .HasForeignKey("ChartTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
