// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raports.Infrastructure.Database;

#nullable disable

namespace Raports.Infrastructure.Migrations
{
    [DbContext(typeof(RaportsDBContext))]
    [Migration("20251125144217_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raports.Domain.Entities.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("For example: 'Kitchen', 'Attic' etc...");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Raports.Domain.Entities.LocationGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Verbal summary of data stored for this location");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("MeasurementGroupID");

                    b.ToTable("LocationGroups");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Measurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Raports.Domain.Entities.MeasurementGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MeasurementID")
                        .HasColumnType("int");

                    b.Property<int>("RaportID")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Combined summary for all location groups");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.HasIndex("RaportID");

                    b.ToTable("MeasurementGroups");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Period", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("For example: 'Daily', 'Weekly', 'Monthly', etc...");

                    b.HasKey("ID");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Raport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of last measurement");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RaportCompletedDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of Raport completion");

                    b.Property<DateTime>("RaportCreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of Raport creation");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of first measurement");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PeriodID");

                    b.HasIndex("StatusID");

                    b.ToTable("Raports");
                });

            modelBuilder.Entity("Raports.Domain.Entities.RequestedLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("RaportID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("RaportID");

                    b.ToTable("RequestedLocations");
                });

            modelBuilder.Entity("Raports.Domain.Entities.RequestedMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MeasurementID")
                        .HasColumnType("int");

                    b.Property<int>("RaportID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.HasIndex("RaportID");

                    b.ToTable("RequestedMeasurements");
                });

            modelBuilder.Entity("Raports.Domain.Entities.SampleGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Time of measurement");

                    b.Property<int>("LocationGroupID")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasComment("Value  of measurement");

                    b.HasKey("ID");

                    b.HasIndex("LocationGroupID");

                    b.ToTable("SampleGroups");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Raports.Domain.Entities.LocationGroup", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.MeasurementGroup", "MeasurementGroup")
                        .WithMany("LocationGroups")
                        .HasForeignKey("MeasurementGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("MeasurementGroup");
                });

            modelBuilder.Entity("Raports.Domain.Entities.MeasurementGroup", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.Raport", "Raport")
                        .WithMany("MeasurementGroups")
                        .HasForeignKey("RaportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Raport");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Raport", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Raports.Domain.Entities.RequestedLocation", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.Raport", "Raport")
                        .WithMany()
                        .HasForeignKey("RaportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Raport");
                });

            modelBuilder.Entity("Raports.Domain.Entities.RequestedMeasurement", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.Raport", "Raport")
                        .WithMany()
                        .HasForeignKey("RaportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Raport");
                });

            modelBuilder.Entity("Raports.Domain.Entities.SampleGroup", b =>
                {
                    b.HasOne("Raports.Domain.Entities.LocationGroup", "LocationGroup")
                        .WithMany("SampleGroups")
                        .HasForeignKey("LocationGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationGroup");
                });

            modelBuilder.Entity("Raports.Domain.Entities.LocationGroup", b =>
                {
                    b.Navigation("SampleGroups");
                });

            modelBuilder.Entity("Raports.Domain.Entities.MeasurementGroup", b =>
                {
                    b.Navigation("LocationGroups");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Raport", b =>
                {
                    b.Navigation("MeasurementGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
