// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raports.Infrastructure.Database;

#nullable disable

namespace Raports.Infrastructure.Migrations
{
    [DbContext(typeof(RaportsDBContext))]
    [Migration("20251029112041_M2")]
    partial class M2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raports.Domain.Entities.Period", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("For example: 'Daily', 'Weekly', 'Monthly', etc...");

                    b.HasKey("ID");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Raport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date when raport was created");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PeriodID");

                    b.HasIndex("RequestID")
                        .IsUnique();

                    b.ToTable("Raports");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Request", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Raport will be generate to this date");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<int>("RaportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestCreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date when request was created");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Raport will be generate from this date");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PeriodID");

                    b.HasIndex("StatusID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Raports.Domain.Entities.RequestStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("What is exactly happening here");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("For example: 'Generated', 'Pending', etc...");

                    b.HasKey("ID");

                    b.ToTable("RequestStatuses");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Raport", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.Request", "Request")
                        .WithOne("Raport")
                        .HasForeignKey("Raports.Domain.Entities.Raport", "RequestID");

                    b.Navigation("Period");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Request", b =>
                {
                    b.HasOne("Raports.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raports.Domain.Entities.RequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Raports.Domain.Entities.Request", b =>
                {
                    b.Navigation("Raport")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
